### ISSUE TITLE
Possible support for Programmer's AID music routines?

### ISSUE THREAD

**Issue by erangell** [a2stuff/intbasic#12]
I'm not sure if this is possible given the use of memory by Prodos, but there were routines in the Programmer's AID ROM which occupied the $D000-$D7FF address space of Integer Basic, such as the music routine.  A disk image with a program that uses it can be found here: https://github.com/erangell/kfest2023/blob/main/INTBSYS_TTD2023.po
LOAD TTD.DRAGON.2023
LIST 1000,1100

**Comment by erangell** [comment]
A DOS 3.3 disk that will boot and play the music is here: https://github.com/erangell/kfest2023/blob/main/TICTACDRAGON.dsk

**Comment by inexorabletash** [comment]
That's definitely memory in use under ProDOS - the Disk II driver specifically - but there are a couple options. 

* Keep that 2k in main 48k memory, and swap it with the ProDOS code when calling into intbasic and back when accessing ProDOS. That approach is already used to swap zero page data so the hooks are already present. The down side is the extra memory. I think intbasic is already using $9E00 up, this would push HIMEM down to $9600 which is the limit where we'd start being bigger than DOS 3.3, and so that would preclude more features. 

* Using LCBank2. ProDOS reserves b2/$D400-DFFF for an AppleTalk driver but that's rarely used. So we could do the same swap trick as above but with that bank. Slower since the copy will require intricate bank switching, but doable and wouldn't impact HIMEM.

**Comment by inexorabletash** [comment]
... or if just the music routine is used, we can swap just that in. https://6502disassembly.com/a2-rom/PA1.html#A2PA1.6 says $D717-D7FF, and some page $02 usage as well. I do T see any dependencies on the rest of the Programmers Aid.

**Comment by inexorabletash** [comment]
Would just the music routines be enough to get your code running under ProDOS? I'm guessing you're looking at a deadline for recording before kfest?

**Comment by erangell** [comment]
There's no urgency for this.  I was just curious about how it could be done.  Great job on porting Intbasic to Prodos!

**Comment by inexorabletash** [comment]
Oh, ugh, I forgot the biggest problem - we need the monitor ROM $F800 in place since IntBASIC depends on that, but can't have that and LC RAM swapped in at the same time, so it's not as simple as extending SwapZP.

Another approach would be to intercept CALL and have it reroute CALL -10473 specifically to an internal/relocated copy of the PA routine.

**Comment by inexorabletash** [comment]
... and for more than the music routine, that would require maintaining a table of entry points (or just a range?) to intercept/remap, which is not out of the question. Plus more ZP locations to preserve. So ... I'll leave this open but not going to try to wedge something in quickly. Sorry!

**Comment by inexorabletash** [comment]
Here, try these out:

[intbasic_system.zip](https://github.com/a2stuff/intbasic/files/11716840/intbasic_system.zip)

This just intercepts CALL for just the one routine.

**Comment by erangell** [comment]
That is amazing!  Thank you very much!
